#!/bin/sh

if [ -x /usr/bin/apt-key ]; then
    /usr/bin/apt-key add /usr/share/keyrings/excito-archive-keyring.gpg
fi

if [ -x /usr/bin/gpg ]; then
	/usr/bin/gpg --import /usr/share/keyrings/excito-hotfix-keyring.gpg
fi

#DEBHELPER#

exit 0
